<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-I0JSKAF" failures="5" tests="25" name="Rest API Testing" time="26.125" errors="0" timestamp="2020-05-17T02:58:34 EDT">
  <testcase classname="testScripts.TC001_GET_ALL_Employees" name="checkGetTime" time="0.007"/>
  <testcase classname="testScripts.TC001_GET_ALL_Employees" name="checkStatusCode" time="0.005"/>
  <testcase classname="testScripts.TC001_GET_ALL_Employees" name="checkStatusLine" time="0.002"/>
  <testcase classname="testScripts.TC001_GET_ALL_Employees" name="checkingBody" time="0.024"/>
  <testcase classname="testScripts.TC001_GET_ALL_Employees" name="checkingContentType" time="0.002"/>
  <testcase classname="testScripts.TC002_GET_SINGLE_Employee_Details" name="checkGetTime" time="0.003"/>
  <testcase classname="testScripts.TC002_GET_SINGLE_Employee_Details" name="checkStatusCode" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [200] but found [400]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [400]
at testScripts.TC002_GET_SINGLE_Employee_Details.checkStatusCode(TC002_GET_SINGLE_Employee_Details.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusCode -->
  <testcase classname="testScripts.TC002_GET_SINGLE_Employee_Details" name="checkStatusLine" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [HTTP/1.1 200 OK] but found [HTTP/1.1 400 Bad Request]">
      <![CDATA[java.lang.AssertionError: expected [HTTP/1.1 200 OK] but found [HTTP/1.1 400 Bad Request]
at testScripts.TC002_GET_SINGLE_Employee_Details.checkStatusLine(TC002_GET_SINGLE_Employee_Details.java:54)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusLine -->
  <testcase classname="testScripts.TC002_GET_SINGLE_Employee_Details" name="checkingBody" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testScripts.TC002_GET_SINGLE_Employee_Details.checkingBody(TC002_GET_SINGLE_Employee_Details.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- checkingBody -->
  <testcase classname="testScripts.TC002_GET_SINGLE_Employee_Details" name="checkingContentType" time="0.002"/>
  <testcase classname="testScripts.TC003_Create_New_Employee" name="checkGetTime" time="0.001"/>
  <testcase classname="testScripts.TC003_Create_New_Employee" name="checkStatusCode" time="0.001"/>
  <testcase classname="testScripts.TC003_Create_New_Employee" name="checkStatusLine" time="0.001"/>
  <testcase classname="testScripts.TC003_Create_New_Employee" name="checkingBody" time="0.001"/>
  <testcase classname="testScripts.TC003_Create_New_Employee" name="checkingContentType" time="0.001"/>
  <testcase classname="testScripts.TC004_Update_Record" name="checkGetTime" time="0.001"/>
  <testcase classname="testScripts.TC004_Update_Record" name="checkStatusCode" time="0.002"/>
  <testcase classname="testScripts.TC004_Update_Record" name="checkStatusLine" time="0.002"/>
  <testcase classname="testScripts.TC004_Update_Record" name="checkingBody" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testScripts.TC004_Update_Record.checkingBody(TC004_Update_Record.java:42)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- checkingBody -->
  <testcase classname="testScripts.TC004_Update_Record" name="checkingContentType" time="0.001"/>
  <testcase classname="testScripts.TC005_Delete_Record" name="checkGetTime" time="0.001"/>
  <testcase classname="testScripts.TC005_Delete_Record" name="checkStatusCode" time="0.001"/>
  <testcase classname="testScripts.TC005_Delete_Record" name="checkStatusLine" time="0.0"/>
  <testcase classname="testScripts.TC005_Delete_Record" name="checkingBody" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testScripts.TC005_Delete_Record.checkingBody(TC005_Delete_Record.java:34)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- checkingBody -->
  <testcase classname="testScripts.TC005_Delete_Record" name="checkingContentType" time="0.002"/>
</testsuite> <!-- Rest API Testing -->
